/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: monsieurmo (https://sketchfab.com/monsieurmo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/halloween-pumpkin-4484260f38114ad0b78da570afc5116c
Title: Halloween pumpkin
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Pumpkin(props) {
  const { nodes, materials } = useGLTF('/halloween_pumpkin.glb')
  return (
    <group {...props} dispose={null} scale={0.0068}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pumpkin_Mat1_0.geometry}
          material={materials['Mat.1']}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/halloween_pumpkin.glb')